package GUI;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import model.DolgozoModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author koncsik.benedek
 */
public class Dolgozok extends javax.swing.JFrame {

    /**
     * Creates new form Dolgozok
     */
    List<DolgozoModel> dolgozok;

    public Dolgozok() throws IOException {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fiuLanyGrp = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lanyokCBB = new javax.swing.JComboBox<>();
        fiukCBB = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        lanyRDB = new javax.swing.JRadioButton();
        fiuRDB = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        legidosebbOLBL = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        osszesKorOLBL = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        hatEveOLBL = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        adatokKorOLBL = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        adatokMiotaDolgOLBL = new javax.swing.JLabel();
        mindkettoCheckB = new javax.swing.JCheckBox();
        mentBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Lányok");

        jLabel2.setText("Fiúk");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Összesítő"));

        fiuLanyGrp.add(lanyRDB);
        lanyRDB.setSelected(true);
        lanyRDB.setText("lány");
        lanyRDB.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                lanyRDBItemStateChanged(evt);
            }
        });

        fiuLanyGrp.add(fiuRDB);
        fiuRDB.setText("fiú");

        jLabel3.setText("legidősebb:");

        legidosebbOLBL.setText(" ");

        jLabel5.setText("összes kor:");

        osszesKorOLBL.setText(" ");

        jLabel7.setText("6 éve dolgozó:");

        hatEveOLBL.setText(" ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lanyRDB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fiuRDB)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(legidosebbOLBL))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(osszesKorOLBL))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hatEveOLBL)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lanyRDB)
                    .addComponent(fiuRDB))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(legidosebbOLBL))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(osszesKorOLBL))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(hatEveOLBL))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Adatok"));

        jLabel9.setText("kor:");

        adatokKorOLBL.setText(" ");

        jLabel11.setText("mióta dolgozik");

        adatokMiotaDolgOLBL.setText(" ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(adatokKorOLBL))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(adatokMiotaDolgOLBL)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(adatokKorOLBL))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(adatokMiotaDolgOLBL))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        mindkettoCheckB.setText("Mindkettő nem");

        mentBTN.setText("Ment");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lanyokCBB, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fiukCBB, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mindkettoCheckB)
                    .addComponent(mentBTN))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(lanyokCBB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fiukCBB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mindkettoCheckB)
                        .addGap(18, 18, 18)
                        .addComponent(mentBTN))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lanyRDBItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_lanyRDBItemStateChanged
        if (this.lanyRDB.isSelected()) {
            osszesitoBeallit(DolgozoModel.LANY);
        } else {
            osszesitoBeallit(DolgozoModel.FIU);
        }

    }//GEN-LAST:event_lanyRDBItemStateChanged

    private void init() throws IOException {
        this.dolgozok = new ArrayList<>();
        dolgozokFeltoltes();
        initOsszesito();
//        for (DolgozoModel dolgozoModel : dolgozok) {
//            System.out.println(dolgozoModel.toString());
//        }
    }

    private void dolgozokFeltoltes() throws IOException {

        Path path = Paths.get("emberek.txt");
        List<String> sorok = Files.readAllLines(path);
        sorok.remove(0);
        for (String sor : sorok) {
            String[] dolgozoSplit = sor.split(";"); //class-ba 
            if (dolgozoSplit.length == 3) {
                this.dolgozok.add(new DolgozoModel(dolgozoSplit[0], Integer.parseInt(dolgozoSplit[1]), dolgozoSplit[2].charAt(0)));
            } else {
                this.dolgozok.add(new DolgozoModel(dolgozoSplit[0], Integer.parseInt(dolgozoSplit[1]), dolgozoSplit[2].charAt(0), Integer.parseInt(dolgozoSplit[3])));
            }
        }
    }

    private void initOsszesito() {
        osszesitoBeallit(DolgozoModel.LANY);
    }

    private void osszesitoBeallit(char nem) {
        this.legidosebbOLBL.setText(String.valueOf(legidosebbDolg(nem)));
        this.osszesKorOLBL.setText(String.valueOf(osszKor(nem)));
        this.hatEveOLBL.setText(hatEveDolgozo(nem, 6));
    }

    private int legidosebbDolg(char nem) {
        int maxKor = this.dolgozok.get(0).getKor();
        int kor;
        for (DolgozoModel dolgozo : dolgozok) {
            kor = dolgozo.getKor();
            if (kor > maxKor && nem == dolgozo.getNeme()) {
                maxKor = kor;
            }
        }
        return maxKor;
    }

    private int osszKor(char nem) {
        int osszKor = 0;
        for (DolgozoModel dolgozo : dolgozok) {
            if (dolgozo.getNeme() == nem) {
                osszKor += dolgozo.getKor();
            }
        }
        return osszKor;
    }

    private String hatEveDolgozo(char nem, int ennyiIdeje) {
        int index = 0;
        String valasz = "nincs";

        while (index < dolgozok.size() && !(dolgozok.get(index).getMunkToltEv() >= ennyiIdeje && dolgozok.get(index).getNeme() == nem)) {
            index++;
        }
        valasz = index >= dolgozok.size() ? valasz : dolgozok.get(index).getNev();
        return valasz;
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dolgozok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dolgozok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dolgozok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dolgozok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Dolgozok().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Dolgozok.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adatokKorOLBL;
    private javax.swing.JLabel adatokMiotaDolgOLBL;
    private javax.swing.ButtonGroup fiuLanyGrp;
    private javax.swing.JRadioButton fiuRDB;
    private javax.swing.JComboBox<String> fiukCBB;
    private javax.swing.JLabel hatEveOLBL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton lanyRDB;
    private javax.swing.JComboBox<String> lanyokCBB;
    private javax.swing.JLabel legidosebbOLBL;
    private javax.swing.JButton mentBTN;
    private javax.swing.JCheckBox mindkettoCheckB;
    private javax.swing.JLabel osszesKorOLBL;
    // End of variables declaration//GEN-END:variables

}
